version: '2'
services:
  mysql:
    image: mysql:5.5.51
    environment:
      MYSQL_ROOT_PASSWORD: fizzbuzz
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile-local
    # command: bundle exec unicorn
    command: bundle exec rails s
    volumes:
      # This seems to work as-is once you expose /Users to the boot2docker vm.
      - .:/app
    links:
      - mysql
    ports:
      - "5000:3000"

volumes:
  mysql_data: