javascripts:
  il_javascripts:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/jquery-ui-1.8.7.custom.min.js
    - public/javascripts/jquery.ui.datepicker-zh-CN.js
    - public/javascripts/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/jquery.tipswift.js
    - public/javascripts/select_org.js
    - public/javascripts/jquery.livequery.js
    - public/javascripts/jquery.notifyBar.js
    - public/javascripts/jquery.watermark.min.js
    - public/javascripts/jquery.cookies.2.2.0.min.js
    - public/javascripts/jquery.blockUI.js
    - public/javascripts/jquery.hotkeys.js
    - public/javascripts/enter2tab.js
    - public/javascripts/bill_selector.js
    - public/javascripts/application.js
  il_ie_javascripts:
    - public/javascripts/ukey.js
    - public/javascripts/web_print.js
  il_ie6_javascripts:
    - public/javascripts/ie6.js

  il_login_javascripts:
    - public/vendors/jquery/jquery-3.2.1.min.js
    - public/vendors/animsition/js/animsition.min.js
    - public/vendors/bootstrap/js/popper.js
    - public/vendors/bootstrap/js/bootstrap.min.js
    - public/vendors/select2/select2.min.js
    - public/vendors/daterangepicker/moment.min.js
    - public/vendors/daterangepicker/daterangepicker.js
    - public/vendors/countdowntime/countdowntime.js
    - public/src/login/js/main.js


stylesheets:
  il_stylesheets:
    - public/stylesheets/web-app-theme/base.css
    - public/stylesheets/web-app-theme/themes/default/style.css
    - public/stylesheets/jquery-ui-css/ui-lightness/jquery-ui-1.8.6.custom.css
    - public/stylesheets/SexyButtons/sexybuttons.css
    - public/stylesheets/fancybox/jquery.fancybox-1.3.4.css
    - public/stylesheets/jquery.tipswift.css
    - public/stylesheets/jquery.notifyBar.css
    - public/stylesheets/web-app-theme/override.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css

  il_ie_stylesheets:
    - public/stylesheets/formtastic_ie6fixes.css
    - public/stylesheets/ie6fixes.css

  il_login_stylesheets:
    - public/vendors/bootstrap/css/bootstrap.min.css
    - public/fonts/font-awesome-4.7.0/css/font-awesome.min.css
    - public/fonts/iconic/css/material-design-iconic-font.min.css
    - public/vendors/animate/animate.css
    - public/vendors/css-hamburgers/hamburgers.min.css
    - public/vendors/animsition/css/animsition.min.css
    - public/vendors/select2/select2.min.css
    - public/vendors/daterangepicker/daterangepicker.css
    - public/src/css/util.css
    - public/src/css/main.css
    

