# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AreasController do
  login_admin
  render_views

  before(:each) do
    @area = Factory(:area)
  end


  describe "GET index" do
    it "should be success" do
      get :index
      response.should be_success
    end
  end

  describe "GET show" do

    it "should be success" do
      get :show, :id => @area
      response.should be_success
    end

    it "assigns the requested area as @transit_company" do
      get :show, :id => @area
      response.should render_template('show')
    end
  end

  describe "GET new" do
    it "should be success" do
      get :new
      response.should be_success
    end
  end

  describe "GET edit" do
    it "assigns the requested transit_company as @area" do
      get :edit, :id => @area
      response.should render_template('edit')
    end
  end

  describe "POST create" do
    before(:each) do
      @attr = Factory.build(:area).attributes
    end
    describe "success" do
      it "能够成功保存中转到货地信息" do
        lambda do
          post :create, :area => @attr
        end.should change(Area,:count).by(1)
      end

      it "redirects to the created area" do
        post :create, :area => @attr
        response.should redirect_to(area_path(assigns(:area)))
      end
    end

    describe "with invalid params" do

      it "re-renders the 'new' template" do
        post :create, :area => {}
        response.should render_template("new")
      end
    end

  end

  describe "PUT update" do
    before :each do
      @attr = {:name => 'changed name'}
    end

    describe "with valid params" do
      it "updates the requested transit_company" do
        put :update, :id => @area, :area=> @attr
        @area.reload
        @area.name.should == @attr[:name]
      end


      it "redirects to the transit_company" do
        put :update, :id => @area,:area => @attr
        response.should redirect_to(area_path(@area))
      end
    end

    describe "with invalid params" do
      it "re-renders the 'edit' template" do
        put :update, :id => @area,:area => {:name => nil}
        response.should render_template("edit")
      end
    end
  end

end

