require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BranchCustomersController do

  # This should return the minimal set of attributes required to create a valid
  # BranchCustomer. As you add validations to BranchCustomer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BranchCustomersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all branch_customers as @branch_customers" do
      branch_customer = BranchCustomer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:branch_customers).should eq([branch_customer])
    end
  end

  describe "GET show" do
    it "assigns the requested branch_customer as @branch_customer" do
      branch_customer = BranchCustomer.create! valid_attributes
      get :show, {:id => branch_customer.to_param}, valid_session
      assigns(:branch_customer).should eq(branch_customer)
    end
  end

  describe "GET new" do
    it "assigns a new branch_customer as @branch_customer" do
      get :new, {}, valid_session
      assigns(:branch_customer).should be_a_new(BranchCustomer)
    end
  end

  describe "GET edit" do
    it "assigns the requested branch_customer as @branch_customer" do
      branch_customer = BranchCustomer.create! valid_attributes
      get :edit, {:id => branch_customer.to_param}, valid_session
      assigns(:branch_customer).should eq(branch_customer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BranchCustomer" do
        expect {
          post :create, {:branch_customer => valid_attributes}, valid_session
        }.to change(BranchCustomer, :count).by(1)
      end

      it "assigns a newly created branch_customer as @branch_customer" do
        post :create, {:branch_customer => valid_attributes}, valid_session
        assigns(:branch_customer).should be_a(BranchCustomer)
        assigns(:branch_customer).should be_persisted
      end

      it "redirects to the created branch_customer" do
        post :create, {:branch_customer => valid_attributes}, valid_session
        response.should redirect_to(BranchCustomer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved branch_customer as @branch_customer" do
        # Trigger the behavior that occurs when invalid params are submitted
        BranchCustomer.any_instance.stub(:save).and_return(false)
        post :create, {:branch_customer => {}}, valid_session
        assigns(:branch_customer).should be_a_new(BranchCustomer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BranchCustomer.any_instance.stub(:save).and_return(false)
        post :create, {:branch_customer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested branch_customer" do
        branch_customer = BranchCustomer.create! valid_attributes
        # Assuming there are no other branch_customers in the database, this
        # specifies that the BranchCustomer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BranchCustomer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => branch_customer.to_param, :branch_customer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested branch_customer as @branch_customer" do
        branch_customer = BranchCustomer.create! valid_attributes
        put :update, {:id => branch_customer.to_param, :branch_customer => valid_attributes}, valid_session
        assigns(:branch_customer).should eq(branch_customer)
      end

      it "redirects to the branch_customer" do
        branch_customer = BranchCustomer.create! valid_attributes
        put :update, {:id => branch_customer.to_param, :branch_customer => valid_attributes}, valid_session
        response.should redirect_to(branch_customer)
      end
    end

    describe "with invalid params" do
      it "assigns the branch_customer as @branch_customer" do
        branch_customer = BranchCustomer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BranchCustomer.any_instance.stub(:save).and_return(false)
        put :update, {:id => branch_customer.to_param, :branch_customer => {}}, valid_session
        assigns(:branch_customer).should eq(branch_customer)
      end

      it "re-renders the 'edit' template" do
        branch_customer = BranchCustomer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BranchCustomer.any_instance.stub(:save).and_return(false)
        put :update, {:id => branch_customer.to_param, :branch_customer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested branch_customer" do
      branch_customer = BranchCustomer.create! valid_attributes
      expect {
        delete :destroy, {:id => branch_customer.to_param}, valid_session
      }.to change(BranchCustomer, :count).by(-1)
    end

    it "redirects to the branch_customers list" do
      branch_customer = BranchCustomer.create! valid_attributes
      delete :destroy, {:id => branch_customer.to_param}, valid_session
      response.should redirect_to(branch_customers_url)
    end
  end

end
