# -*- encoding : utf-8 -*-
#coding: utf-8
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ConfigTransitsController do
  login_admin
  render_views

  before(:each) do
    @config_transit = Factory(:config_transit)
  end


  describe "GET index" do
    it "assigns all config_transits as @config_transits" do
      get :index
      response.should be_success
    end
  end

  describe "GET show" do

    it "should be success" do
      get :show, :id => @config_transit
      response.should be_success
    end

    it "assigns the requested config_transit as @config_transit" do
      get :show, :id => @config_transit
      response.should render_template('show')
    end
  end

  describe "GET new" do
    it "should be success" do
      get :new
      response.should be_success
    end
  end

  describe "GET edit" do
    it "assigns the requested config_transit as @config_transit" do
      get :edit, :id => @config_transit
      response.should render_template('edit')
    end
  end

  describe "POST create" do
    before(:each) do
      @attr = Factory.build(:config_transit).attributes
    end
    describe "success" do
      it "能够成功保存转账手续费设置信息" do
        lambda do
          post :create, :config_transit => @attr
        end.should change(ConfigTransit,:count).by(1)
      end

      it "redirects to the created config_transit" do
        post :create, :config_transit => @attr
        response.should redirect_to(config_transit_path(assigns(:config_transit)))
      end
    end

    describe "with invalid params" do
      it "re-renders the 'new' template" do
        post :create, :config_transit => {:rate => nil}
        response.should render_template("new")
      end
    end

  end

  describe "PUT update" do
    before :each do
      @attr = {:name => "转账手续费修改"}
    end

    describe "with valid params" do
      it "updates the requested config_transit" do
        put :update, :id => @config_transit, :config_transit => @attr
        @config_transit.reload
        @config_transit.name.should == @attr[:name]
      end


      it "redirects to the config_transit" do
        put :update, :id => @config_transit,:config_transit => @attr
        response.should redirect_to(config_transit_path(@config_transit))
      end
    end

    describe "with invalid params" do
      it "re-renders the 'edit' template" do
        put :update, :id => @config_transit,:config_transit => {:name => nil,:rate => nil}
        response.should render_template("edit")
      end
    end

  end

  describe "DELETE destroy" do
    it "destroys the requested config_transit" do
      lambda do
        delete :destroy, :id => @config_transit
      end.should change(ConfigTransit,:count).by(-1)
    end

    it "redirects to the config_transits list" do
      delete :destroy, :id => @config_transit
      response.should redirect_to(config_transits_url)
    end
  end
end

