require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DebtBillsController do
  login_admin
  render_views

  # This should return the minimal set of attributes required to create a valid
  # DebtBill. As you add validations to DebtBill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    Factory.build(:debt_bill).attributes.delete_if {|k,v| [:id,:created_at,:updated_at].include? k.to_sym}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DebtBillsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all debt_bills as @debt_bills" do
      debt_bill = Factory(:debt_bill)
      get :index
      #assigns(:debt_bills).should eq([debt_bill])
    end
  end

  describe "GET show" do
    it "assigns the requested debt_bill as @debt_bill" do
      debt_bill = Factory(:debt_bill)
      get :show, :id => debt_bill
      assigns(:debt_bill).should eq(debt_bill)
    end
  end

  describe "GET new" do
    it "assigns a new debt_bill as @debt_bill" do
      get :new
      assigns(:debt_bill).should be_a_new(DebtBill)
    end
  end

  describe "GET edit" do
    it "assigns the requested debt_bill as @debt_bill" do
      debt_bill = Factory(:debt_bill)
      get :edit, :id => debt_bill
      assigns(:debt_bill).should eq(debt_bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DebtBill" do
        expect {
          post :create, :debt_bill => valid_attributes,:bill_ids => [1]
        }.to change(DebtBill, :count).by(1)
      end

      it "assigns a newly created debt_bill as @debt_bill" do
        post :create, :debt_bill => valid_attributes,:bill_ids => [1]

        assigns(:debt_bill).should be_a(DebtBill)
        assigns(:debt_bill).should be_persisted
      end

      it "redirects to the created debt_bill" do
        post :create, :debt_bill => valid_attributes,:bill_ids => [1]

        response.should redirect_to(DebtBill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved debt_bill as @debt_bill" do
        # Trigger the behavior that occurs when invalid params are submitted
        post :create, :debt_bill => {},:bill_ids => [1]

        assigns(:debt_bill).should be_a_new(DebtBill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        post :create, :debt_bill => {},:bill_ids => [1]

        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    before :each do
      @debt_bill = Factory(:debt_bill)
    end
    describe "with valid params" do
      it "updates the requested debt_bill" do
        put :update, :id => @debt_bill, :debt_bill => {'note' => 'params'}
      end

      it "assigns the requested debt_bill as @debt_bill" do
        put :update, :id => @debt_bill, :debt_bill => valid_attributes
        assigns(:debt_bill).should eq(@debt_bill)
      end

      it "redirects to the debt_bill" do
        put :update, :id => @debt_bill, :debt_bill => valid_attributes
        response.should redirect_to(@debt_bill)
      end
    end

    describe "with invalid params" do
      it "assigns the debt_bill as @debt_bill" do
        put :update, :id => @debt_bill, :debt_bill => {:org_id => ""}
        assigns(:debt_bill).should eq(@debt_bill)
      end

      it "re-renders the 'edit' template" do
        put :update, :id => @debt_bill, :debt_bill => {:org_id => ""}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    before :each do
      @debt_bill = Factory(:debt_bill)
    end
    it "destroys the requested debt_bill" do
      expect {
        delete :destroy, :id => @debt_bill
      }.to change(DebtBill, :count).by(-1)
    end

    it "redirects to the debt_bills list" do
      delete :destroy, :id => @debt_bill
      response.should redirect_to(debt_bills_url)
    end
  end
end
