require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeliverRegionsController do
  login_admin
  render_views

  describe "GET index" do
    before(:each) do
      @deliver_region ||= Factory(:deliver_region)
    end

    it "should be success" do
      get :index
      response.should be_success
    end
  end

  describe "GET show" do
    before(:each) do
      @deliver_region ||= Factory(:deliver_region)
    end

    it "should render 'show'" do
      get :show, :id => @deliver_region
      response.should render_template('show')
    end
  end

  describe "GET new" do
    it "should be sucesss" do
      get :new
      response.should be_success
    end
    it "should render template 'new'" do
      get :new
      response.should render_template('new')
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "the deliver_region should success create" do
        lambda do
          post :create,:deliver_region => {
            :org_id => Factory(:zz),
            :name => "deliver region",
            :province_code => "450001",
            :city_code => "450089",
            :district_code => "450090"
          }
        end.should change(DeliverRegion,:count).by(1)
      end

      it "redirects to the created deliver_region" do
        post :create,:deliver_region => {
            :org_id => Factory(:zz),
            :name => "deliver region",
            :province_code => "450001",
            :city_code => "450089",
            :district_code => "450090"
          }

        response.should redirect_to(assigns[:deliver_region])
      end
    end

    describe "with invalid params" do
      it "re-renders the 'new' template" do
        post :create, :deliver_region => {:order_by => 1}
        response.should render_template('new')
      end
    end
  end


  describe "DELETE destroy" do
    before(:each) do
      @deliver_region ||= Factory(:deliver_region)
    end

    it "destroys the requested deliver_region" do
      lambda do
        delete :destroy ,:id => @deliver_region
      end.should change(DeliverRegion,:count).by(-1)
    end

    it "redirects to the deliver_regions list" do
      delete :destroy, :id => @deliver_region
      response.should redirect_to(deliver_regions_url)
    end
  end
end
