require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FeeUnitsController do

  # This should return the minimal set of attributes required to create a valid
  # FeeUnit. As you add validations to FeeUnit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FeeUnitsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all fee_units as @fee_units" do
      fee_unit = FeeUnit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fee_units).should eq([fee_unit])
    end
  end

  describe "GET show" do
    it "assigns the requested fee_unit as @fee_unit" do
      fee_unit = FeeUnit.create! valid_attributes
      get :show, {:id => fee_unit.to_param}, valid_session
      assigns(:fee_unit).should eq(fee_unit)
    end
  end

  describe "GET new" do
    it "assigns a new fee_unit as @fee_unit" do
      get :new, {}, valid_session
      assigns(:fee_unit).should be_a_new(FeeUnit)
    end
  end

  describe "GET edit" do
    it "assigns the requested fee_unit as @fee_unit" do
      fee_unit = FeeUnit.create! valid_attributes
      get :edit, {:id => fee_unit.to_param}, valid_session
      assigns(:fee_unit).should eq(fee_unit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FeeUnit" do
        expect {
          post :create, {:fee_unit => valid_attributes}, valid_session
        }.to change(FeeUnit, :count).by(1)
      end

      it "assigns a newly created fee_unit as @fee_unit" do
        post :create, {:fee_unit => valid_attributes}, valid_session
        assigns(:fee_unit).should be_a(FeeUnit)
        assigns(:fee_unit).should be_persisted
      end

      it "redirects to the created fee_unit" do
        post :create, {:fee_unit => valid_attributes}, valid_session
        response.should redirect_to(FeeUnit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fee_unit as @fee_unit" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeeUnit.any_instance.stub(:save).and_return(false)
        post :create, {:fee_unit => {}}, valid_session
        assigns(:fee_unit).should be_a_new(FeeUnit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeeUnit.any_instance.stub(:save).and_return(false)
        post :create, {:fee_unit => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fee_unit" do
        fee_unit = FeeUnit.create! valid_attributes
        # Assuming there are no other fee_units in the database, this
        # specifies that the FeeUnit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FeeUnit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => fee_unit.to_param, :fee_unit => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested fee_unit as @fee_unit" do
        fee_unit = FeeUnit.create! valid_attributes
        put :update, {:id => fee_unit.to_param, :fee_unit => valid_attributes}, valid_session
        assigns(:fee_unit).should eq(fee_unit)
      end

      it "redirects to the fee_unit" do
        fee_unit = FeeUnit.create! valid_attributes
        put :update, {:id => fee_unit.to_param, :fee_unit => valid_attributes}, valid_session
        response.should redirect_to(fee_unit)
      end
    end

    describe "with invalid params" do
      it "assigns the fee_unit as @fee_unit" do
        fee_unit = FeeUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeeUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => fee_unit.to_param, :fee_unit => {}}, valid_session
        assigns(:fee_unit).should eq(fee_unit)
      end

      it "re-renders the 'edit' template" do
        fee_unit = FeeUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeeUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => fee_unit.to_param, :fee_unit => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fee_unit" do
      fee_unit = FeeUnit.create! valid_attributes
      expect {
        delete :destroy, {:id => fee_unit.to_param}, valid_session
      }.to change(FeeUnit, :count).by(-1)
    end

    it "redirects to the fee_units list" do
      fee_unit = FeeUnit.create! valid_attributes
      delete :destroy, {:id => fee_unit.to_param}, valid_session
      response.should redirect_to(fee_units_url)
    end
  end

end
