require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LocalTownReturnBillsController do

  # This should return the minimal set of attributes required to create a valid
  # LocalTownReturnBill. As you add validations to LocalTownReturnBill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LocalTownReturnBillsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all local_town_return_bills as @local_town_return_bills" do
      local_town_return_bill = LocalTownReturnBill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:local_town_return_bills).should eq([local_town_return_bill])
    end
  end

  describe "GET show" do
    it "assigns the requested local_town_return_bill as @local_town_return_bill" do
      local_town_return_bill = LocalTownReturnBill.create! valid_attributes
      get :show, {:id => local_town_return_bill.to_param}, valid_session
      assigns(:local_town_return_bill).should eq(local_town_return_bill)
    end
  end

  describe "GET new" do
    it "assigns a new local_town_return_bill as @local_town_return_bill" do
      get :new, {}, valid_session
      assigns(:local_town_return_bill).should be_a_new(LocalTownReturnBill)
    end
  end

  describe "GET edit" do
    it "assigns the requested local_town_return_bill as @local_town_return_bill" do
      local_town_return_bill = LocalTownReturnBill.create! valid_attributes
      get :edit, {:id => local_town_return_bill.to_param}, valid_session
      assigns(:local_town_return_bill).should eq(local_town_return_bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LocalTownReturnBill" do
        expect {
          post :create, {:local_town_return_bill => valid_attributes}, valid_session
        }.to change(LocalTownReturnBill, :count).by(1)
      end

      it "assigns a newly created local_town_return_bill as @local_town_return_bill" do
        post :create, {:local_town_return_bill => valid_attributes}, valid_session
        assigns(:local_town_return_bill).should be_a(LocalTownReturnBill)
        assigns(:local_town_return_bill).should be_persisted
      end

      it "redirects to the created local_town_return_bill" do
        post :create, {:local_town_return_bill => valid_attributes}, valid_session
        response.should redirect_to(LocalTownReturnBill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved local_town_return_bill as @local_town_return_bill" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocalTownReturnBill.any_instance.stub(:save).and_return(false)
        post :create, {:local_town_return_bill => {}}, valid_session
        assigns(:local_town_return_bill).should be_a_new(LocalTownReturnBill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocalTownReturnBill.any_instance.stub(:save).and_return(false)
        post :create, {:local_town_return_bill => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested local_town_return_bill" do
        local_town_return_bill = LocalTownReturnBill.create! valid_attributes
        # Assuming there are no other local_town_return_bills in the database, this
        # specifies that the LocalTownReturnBill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LocalTownReturnBill.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => local_town_return_bill.to_param, :local_town_return_bill => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested local_town_return_bill as @local_town_return_bill" do
        local_town_return_bill = LocalTownReturnBill.create! valid_attributes
        put :update, {:id => local_town_return_bill.to_param, :local_town_return_bill => valid_attributes}, valid_session
        assigns(:local_town_return_bill).should eq(local_town_return_bill)
      end

      it "redirects to the local_town_return_bill" do
        local_town_return_bill = LocalTownReturnBill.create! valid_attributes
        put :update, {:id => local_town_return_bill.to_param, :local_town_return_bill => valid_attributes}, valid_session
        response.should redirect_to(local_town_return_bill)
      end
    end

    describe "with invalid params" do
      it "assigns the local_town_return_bill as @local_town_return_bill" do
        local_town_return_bill = LocalTownReturnBill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocalTownReturnBill.any_instance.stub(:save).and_return(false)
        put :update, {:id => local_town_return_bill.to_param, :local_town_return_bill => {}}, valid_session
        assigns(:local_town_return_bill).should eq(local_town_return_bill)
      end

      it "re-renders the 'edit' template" do
        local_town_return_bill = LocalTownReturnBill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocalTownReturnBill.any_instance.stub(:save).and_return(false)
        put :update, {:id => local_town_return_bill.to_param, :local_town_return_bill => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested local_town_return_bill" do
      local_town_return_bill = LocalTownReturnBill.create! valid_attributes
      expect {
        delete :destroy, {:id => local_town_return_bill.to_param}, valid_session
      }.to change(LocalTownReturnBill, :count).by(-1)
    end

    it "redirects to the local_town_return_bills list" do
      local_town_return_bill = LocalTownReturnBill.create! valid_attributes
      delete :destroy, {:id => local_town_return_bill.to_param}, valid_session
      response.should redirect_to(local_town_return_bills_url)
    end
  end

end
