require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrgLoadsController do

  # This should return the minimal set of attributes required to create a valid
  # OrgLoad. As you add validations to OrgLoad, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrgLoadsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all org_loads as @org_loads" do
      org_load = OrgLoad.create! valid_attributes
      get :index, {}, valid_session
      assigns(:org_loads).should eq([org_load])
    end
  end

  describe "GET show" do
    it "assigns the requested org_load as @org_load" do
      org_load = OrgLoad.create! valid_attributes
      get :show, {:id => org_load.to_param}, valid_session
      assigns(:org_load).should eq(org_load)
    end
  end

  describe "GET new" do
    it "assigns a new org_load as @org_load" do
      get :new, {}, valid_session
      assigns(:org_load).should be_a_new(OrgLoad)
    end
  end

  describe "GET edit" do
    it "assigns the requested org_load as @org_load" do
      org_load = OrgLoad.create! valid_attributes
      get :edit, {:id => org_load.to_param}, valid_session
      assigns(:org_load).should eq(org_load)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrgLoad" do
        expect {
          post :create, {:org_load => valid_attributes}, valid_session
        }.to change(OrgLoad, :count).by(1)
      end

      it "assigns a newly created org_load as @org_load" do
        post :create, {:org_load => valid_attributes}, valid_session
        assigns(:org_load).should be_a(OrgLoad)
        assigns(:org_load).should be_persisted
      end

      it "redirects to the created org_load" do
        post :create, {:org_load => valid_attributes}, valid_session
        response.should redirect_to(OrgLoad.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved org_load as @org_load" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrgLoad.any_instance.stub(:save).and_return(false)
        post :create, {:org_load => {}}, valid_session
        assigns(:org_load).should be_a_new(OrgLoad)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrgLoad.any_instance.stub(:save).and_return(false)
        post :create, {:org_load => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested org_load" do
        org_load = OrgLoad.create! valid_attributes
        # Assuming there are no other org_loads in the database, this
        # specifies that the OrgLoad created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrgLoad.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => org_load.to_param, :org_load => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested org_load as @org_load" do
        org_load = OrgLoad.create! valid_attributes
        put :update, {:id => org_load.to_param, :org_load => valid_attributes}, valid_session
        assigns(:org_load).should eq(org_load)
      end

      it "redirects to the org_load" do
        org_load = OrgLoad.create! valid_attributes
        put :update, {:id => org_load.to_param, :org_load => valid_attributes}, valid_session
        response.should redirect_to(org_load)
      end
    end

    describe "with invalid params" do
      it "assigns the org_load as @org_load" do
        org_load = OrgLoad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrgLoad.any_instance.stub(:save).and_return(false)
        put :update, {:id => org_load.to_param, :org_load => {}}, valid_session
        assigns(:org_load).should eq(org_load)
      end

      it "re-renders the 'edit' template" do
        org_load = OrgLoad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrgLoad.any_instance.stub(:save).and_return(false)
        put :update, {:id => org_load.to_param, :org_load => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested org_load" do
      org_load = OrgLoad.create! valid_attributes
      expect {
        delete :destroy, {:id => org_load.to_param}, valid_session
      }.to change(OrgLoad, :count).by(-1)
    end

    it "redirects to the org_loads list" do
      org_load = OrgLoad.create! valid_attributes
      delete :destroy, {:id => org_load.to_param}, valid_session
      response.should redirect_to(org_loads_url)
    end
  end

end
