require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrgSortingsController do

  # This should return the minimal set of attributes required to create a valid
  # OrgSorting. As you add validations to OrgSorting, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrgSortingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all org_sortings as @org_sortings" do
      org_sorting = OrgSorting.create! valid_attributes
      get :index, {}, valid_session
      assigns(:org_sortings).should eq([org_sorting])
    end
  end

  describe "GET show" do
    it "assigns the requested org_sorting as @org_sorting" do
      org_sorting = OrgSorting.create! valid_attributes
      get :show, {:id => org_sorting.to_param}, valid_session
      assigns(:org_sorting).should eq(org_sorting)
    end
  end

  describe "GET new" do
    it "assigns a new org_sorting as @org_sorting" do
      get :new, {}, valid_session
      assigns(:org_sorting).should be_a_new(OrgSorting)
    end
  end

  describe "GET edit" do
    it "assigns the requested org_sorting as @org_sorting" do
      org_sorting = OrgSorting.create! valid_attributes
      get :edit, {:id => org_sorting.to_param}, valid_session
      assigns(:org_sorting).should eq(org_sorting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrgSorting" do
        expect {
          post :create, {:org_sorting => valid_attributes}, valid_session
        }.to change(OrgSorting, :count).by(1)
      end

      it "assigns a newly created org_sorting as @org_sorting" do
        post :create, {:org_sorting => valid_attributes}, valid_session
        assigns(:org_sorting).should be_a(OrgSorting)
        assigns(:org_sorting).should be_persisted
      end

      it "redirects to the created org_sorting" do
        post :create, {:org_sorting => valid_attributes}, valid_session
        response.should redirect_to(OrgSorting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved org_sorting as @org_sorting" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrgSorting.any_instance.stub(:save).and_return(false)
        post :create, {:org_sorting => {}}, valid_session
        assigns(:org_sorting).should be_a_new(OrgSorting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrgSorting.any_instance.stub(:save).and_return(false)
        post :create, {:org_sorting => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested org_sorting" do
        org_sorting = OrgSorting.create! valid_attributes
        # Assuming there are no other org_sortings in the database, this
        # specifies that the OrgSorting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrgSorting.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => org_sorting.to_param, :org_sorting => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested org_sorting as @org_sorting" do
        org_sorting = OrgSorting.create! valid_attributes
        put :update, {:id => org_sorting.to_param, :org_sorting => valid_attributes}, valid_session
        assigns(:org_sorting).should eq(org_sorting)
      end

      it "redirects to the org_sorting" do
        org_sorting = OrgSorting.create! valid_attributes
        put :update, {:id => org_sorting.to_param, :org_sorting => valid_attributes}, valid_session
        response.should redirect_to(org_sorting)
      end
    end

    describe "with invalid params" do
      it "assigns the org_sorting as @org_sorting" do
        org_sorting = OrgSorting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrgSorting.any_instance.stub(:save).and_return(false)
        put :update, {:id => org_sorting.to_param, :org_sorting => {}}, valid_session
        assigns(:org_sorting).should eq(org_sorting)
      end

      it "re-renders the 'edit' template" do
        org_sorting = OrgSorting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrgSorting.any_instance.stub(:save).and_return(false)
        put :update, {:id => org_sorting.to_param, :org_sorting => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested org_sorting" do
      org_sorting = OrgSorting.create! valid_attributes
      expect {
        delete :destroy, {:id => org_sorting.to_param}, valid_session
      }.to change(OrgSorting, :count).by(-1)
    end

    it "redirects to the org_sortings list" do
      org_sorting = OrgSorting.create! valid_attributes
      delete :destroy, {:id => org_sorting.to_param}, valid_session
      response.should redirect_to(org_sortings_url)
    end
  end

end
