require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PriceListsController do

  # This should return the minimal set of attributes required to create a valid
  # PriceList. As you add validations to PriceList, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PriceListsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all price_lists as @price_lists" do
      price_list = PriceList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:price_lists).should eq([price_list])
    end
  end

  describe "GET show" do
    it "assigns the requested price_list as @price_list" do
      price_list = PriceList.create! valid_attributes
      get :show, {:id => price_list.to_param}, valid_session
      assigns(:price_list).should eq(price_list)
    end
  end

  describe "GET new" do
    it "assigns a new price_list as @price_list" do
      get :new, {}, valid_session
      assigns(:price_list).should be_a_new(PriceList)
    end
  end

  describe "GET edit" do
    it "assigns the requested price_list as @price_list" do
      price_list = PriceList.create! valid_attributes
      get :edit, {:id => price_list.to_param}, valid_session
      assigns(:price_list).should eq(price_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PriceList" do
        expect {
          post :create, {:price_list => valid_attributes}, valid_session
        }.to change(PriceList, :count).by(1)
      end

      it "assigns a newly created price_list as @price_list" do
        post :create, {:price_list => valid_attributes}, valid_session
        assigns(:price_list).should be_a(PriceList)
        assigns(:price_list).should be_persisted
      end

      it "redirects to the created price_list" do
        post :create, {:price_list => valid_attributes}, valid_session
        response.should redirect_to(PriceList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved price_list as @price_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceList.any_instance.stub(:save).and_return(false)
        post :create, {:price_list => {}}, valid_session
        assigns(:price_list).should be_a_new(PriceList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceList.any_instance.stub(:save).and_return(false)
        post :create, {:price_list => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested price_list" do
        price_list = PriceList.create! valid_attributes
        # Assuming there are no other price_lists in the database, this
        # specifies that the PriceList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PriceList.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => price_list.to_param, :price_list => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested price_list as @price_list" do
        price_list = PriceList.create! valid_attributes
        put :update, {:id => price_list.to_param, :price_list => valid_attributes}, valid_session
        assigns(:price_list).should eq(price_list)
      end

      it "redirects to the price_list" do
        price_list = PriceList.create! valid_attributes
        put :update, {:id => price_list.to_param, :price_list => valid_attributes}, valid_session
        response.should redirect_to(price_list)
      end
    end

    describe "with invalid params" do
      it "assigns the price_list as @price_list" do
        price_list = PriceList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceList.any_instance.stub(:save).and_return(false)
        put :update, {:id => price_list.to_param, :price_list => {}}, valid_session
        assigns(:price_list).should eq(price_list)
      end

      it "re-renders the 'edit' template" do
        price_list = PriceList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceList.any_instance.stub(:save).and_return(false)
        put :update, {:id => price_list.to_param, :price_list => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested price_list" do
      price_list = PriceList.create! valid_attributes
      expect {
        delete :destroy, {:id => price_list.to_param}, valid_session
      }.to change(PriceList, :count).by(-1)
    end

    it "redirects to the price_lists list" do
      price_list = PriceList.create! valid_attributes
      delete :destroy, {:id => price_list.to_param}, valid_session
      response.should redirect_to(price_lists_url)
    end
  end

end
