require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegionsController do

  # This should return the minimal set of attributes required to create a valid
  # Region. As you add validations to Region, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all regions as @regions" do
      region = Region.create! valid_attributes
      get :index, {}, valid_session
      assigns(:regions).should eq([region])
    end
  end

  describe "GET show" do
    it "assigns the requested region as @region" do
      region = Region.create! valid_attributes
      get :show, {:id => region.to_param}, valid_session
      assigns(:region).should eq(region)
    end
  end

  describe "GET new" do
    it "assigns a new region as @region" do
      get :new, {}, valid_session
      assigns(:region).should be_a_new(Region)
    end
  end

  describe "GET edit" do
    it "assigns the requested region as @region" do
      region = Region.create! valid_attributes
      get :edit, {:id => region.to_param}, valid_session
      assigns(:region).should eq(region)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Region" do
        expect {
          post :create, {:region => valid_attributes}, valid_session
        }.to change(Region, :count).by(1)
      end

      it "assigns a newly created region as @region" do
        post :create, {:region => valid_attributes}, valid_session
        assigns(:region).should be_a(Region)
        assigns(:region).should be_persisted
      end

      it "redirects to the created region" do
        post :create, {:region => valid_attributes}, valid_session
        response.should redirect_to(Region.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved region as @region" do
        # Trigger the behavior that occurs when invalid params are submitted
        Region.any_instance.stub(:save).and_return(false)
        post :create, {:region => {}}, valid_session
        assigns(:region).should be_a_new(Region)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Region.any_instance.stub(:save).and_return(false)
        post :create, {:region => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested region" do
        region = Region.create! valid_attributes
        # Assuming there are no other regions in the database, this
        # specifies that the Region created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Region.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => region.to_param, :region => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested region as @region" do
        region = Region.create! valid_attributes
        put :update, {:id => region.to_param, :region => valid_attributes}, valid_session
        assigns(:region).should eq(region)
      end

      it "redirects to the region" do
        region = Region.create! valid_attributes
        put :update, {:id => region.to_param, :region => valid_attributes}, valid_session
        response.should redirect_to(region)
      end
    end

    describe "with invalid params" do
      it "assigns the region as @region" do
        region = Region.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Region.any_instance.stub(:save).and_return(false)
        put :update, {:id => region.to_param, :region => {}}, valid_session
        assigns(:region).should eq(region)
      end

      it "re-renders the 'edit' template" do
        region = Region.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Region.any_instance.stub(:save).and_return(false)
        put :update, {:id => region.to_param, :region => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested region" do
      region = Region.create! valid_attributes
      expect {
        delete :destroy, {:id => region.to_param}, valid_session
      }.to change(Region, :count).by(-1)
    end

    it "redirects to the regions list" do
      region = Region.create! valid_attributes
      delete :destroy, {:id => region.to_param}, valid_session
      response.should redirect_to(regions_url)
    end
  end

end
