# -*- encoding : utf-8 -*-
#coding: utf-8
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SendListPostsController do
  login_admin
  render_views

  before(:each) do
    @send_list_post = Factory(:send_list_post)
  end


  describe "GET index" do
    it "assigns all send_list_posts as @send_list_posts" do
      get :index
      response.should be_success
    end
  end

  describe "GET show" do

    it "should be success" do
      get :show, :id => @send_list_post
      response.should be_success
    end

    it "assigns the requested send_list_post as @send_list_post" do
      get :show, :id => @send_list_post
      response.should render_template('show')
    end
  end

  describe "GET new" do
    it "should be success" do
      get :new
      response.should be_success
    end
  end

  describe "POST create" do
    before(:each) do
      @attr = Factory.build(:send_list_post).attributes
      @bill_ids = [Factory(:hand_bill).id]
    end
    describe "success" do
      it "能够成功保存票据信息" do
        lambda do
          post :create, :send_list_post => @attr,:bill_ids => @bill_ids
        end.should change(SendListPost,:count).by(1)
      end

      it "redirects to the created send_list_post" do
        post :create, :send_list_post => @attr,:bill_ids => @bill_ids
        response.should redirect_to(send_list_post_path(assigns(:send_list_post)))
      end
    end

    describe "with invalid params" do
      it "re-renders the 'new' template" do
        post :create, :send_list_post => {},:bill_ids => @bill_ids
        response.should render_template("new")
      end
    end

  end

  describe "DELETE destroy" do
    it "destroys the requested send_list_post" do
      lambda do
        delete :destroy, :id => @send_list_post
      end.should change(SendListPost,:count).by(-1)
    end

    it "redirects to the send_list_posts list" do
      delete :destroy, :id => @send_list_post
      response.should redirect_to(send_list_posts_url)
    end
  end
  describe "GET search" do
    it "should be success" do
      get :search
      response.should be_success
    end
    it "should render 'search'" do
      get :search
      response.should render_template('search')
    end
  end
end

