require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SingleVoteConfigWithOrgsController do

  # This should return the minimal set of attributes required to create a valid
  # SingleVoteConfigWithOrg. As you add validations to SingleVoteConfigWithOrg, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SingleVoteConfigWithOrgsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all single_vote_config_with_orgs as @single_vote_config_with_orgs" do
      single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
      get :index, {}, valid_session
      assigns(:single_vote_config_with_orgs).should eq([single_vote_config_with_org])
    end
  end

  describe "GET show" do
    it "assigns the requested single_vote_config_with_org as @single_vote_config_with_org" do
      single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
      get :show, {:id => single_vote_config_with_org.to_param}, valid_session
      assigns(:single_vote_config_with_org).should eq(single_vote_config_with_org)
    end
  end

  describe "GET new" do
    it "assigns a new single_vote_config_with_org as @single_vote_config_with_org" do
      get :new, {}, valid_session
      assigns(:single_vote_config_with_org).should be_a_new(SingleVoteConfigWithOrg)
    end
  end

  describe "GET edit" do
    it "assigns the requested single_vote_config_with_org as @single_vote_config_with_org" do
      single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
      get :edit, {:id => single_vote_config_with_org.to_param}, valid_session
      assigns(:single_vote_config_with_org).should eq(single_vote_config_with_org)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SingleVoteConfigWithOrg" do
        expect {
          post :create, {:single_vote_config_with_org => valid_attributes}, valid_session
        }.to change(SingleVoteConfigWithOrg, :count).by(1)
      end

      it "assigns a newly created single_vote_config_with_org as @single_vote_config_with_org" do
        post :create, {:single_vote_config_with_org => valid_attributes}, valid_session
        assigns(:single_vote_config_with_org).should be_a(SingleVoteConfigWithOrg)
        assigns(:single_vote_config_with_org).should be_persisted
      end

      it "redirects to the created single_vote_config_with_org" do
        post :create, {:single_vote_config_with_org => valid_attributes}, valid_session
        response.should redirect_to(SingleVoteConfigWithOrg.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved single_vote_config_with_org as @single_vote_config_with_org" do
        # Trigger the behavior that occurs when invalid params are submitted
        SingleVoteConfigWithOrg.any_instance.stub(:save).and_return(false)
        post :create, {:single_vote_config_with_org => {}}, valid_session
        assigns(:single_vote_config_with_org).should be_a_new(SingleVoteConfigWithOrg)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SingleVoteConfigWithOrg.any_instance.stub(:save).and_return(false)
        post :create, {:single_vote_config_with_org => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested single_vote_config_with_org" do
        single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
        # Assuming there are no other single_vote_config_with_orgs in the database, this
        # specifies that the SingleVoteConfigWithOrg created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SingleVoteConfigWithOrg.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => single_vote_config_with_org.to_param, :single_vote_config_with_org => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested single_vote_config_with_org as @single_vote_config_with_org" do
        single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
        put :update, {:id => single_vote_config_with_org.to_param, :single_vote_config_with_org => valid_attributes}, valid_session
        assigns(:single_vote_config_with_org).should eq(single_vote_config_with_org)
      end

      it "redirects to the single_vote_config_with_org" do
        single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
        put :update, {:id => single_vote_config_with_org.to_param, :single_vote_config_with_org => valid_attributes}, valid_session
        response.should redirect_to(single_vote_config_with_org)
      end
    end

    describe "with invalid params" do
      it "assigns the single_vote_config_with_org as @single_vote_config_with_org" do
        single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SingleVoteConfigWithOrg.any_instance.stub(:save).and_return(false)
        put :update, {:id => single_vote_config_with_org.to_param, :single_vote_config_with_org => {}}, valid_session
        assigns(:single_vote_config_with_org).should eq(single_vote_config_with_org)
      end

      it "re-renders the 'edit' template" do
        single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SingleVoteConfigWithOrg.any_instance.stub(:save).and_return(false)
        put :update, {:id => single_vote_config_with_org.to_param, :single_vote_config_with_org => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested single_vote_config_with_org" do
      single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
      expect {
        delete :destroy, {:id => single_vote_config_with_org.to_param}, valid_session
      }.to change(SingleVoteConfigWithOrg, :count).by(-1)
    end

    it "redirects to the single_vote_config_with_orgs list" do
      single_vote_config_with_org = SingleVoteConfigWithOrg.create! valid_attributes
      delete :destroy, {:id => single_vote_config_with_org.to_param}, valid_session
      response.should redirect_to(single_vote_config_with_orgs_url)
    end
  end

end
