<script language="javascript">
/**********运输协议单套打设置*************/

  ysxy_PaperWidth = 176;  //毫米
  ysxy_PaperHeight = 173;  //毫米
  ysxy_OffsetX = 0;  //毫米
  ysxy_OffsetY = -8.0;  //毫米
  ysxy_fontColor = "000000";
  ysxy_fontSize = 13;

/**********运输委托书套打设置*************/

  yswts_PaperWidth = 203.5;  //毫米
  yswts_PaperHeight = 297;  //毫米
  yswts_OffsetX = 0;  //毫米
  yswts_OffsetY = 0;  //毫米
  yswts_fontColor = "000000";
  yswts_fontSize = 13;

</script>